// <auto-generated />
using BIC_FHTW.Database.DatabaseContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BIC_FHTW.Database.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20230910102457_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.4");

            modelBuilder.Entity("BIC_FHTW.Database.Models.DiscordUser", b =>
                {
                    b.Property<ulong>("DiscordUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActivationToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StudentMail")
                        .HasColumnType("TEXT");

                    b.HasKey("DiscordUserId");

                    b.HasIndex("DiscordUserId")
                        .IsUnique();

                    b.HasIndex("StudentMail")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BIC_FHTW.Database.Models.DiscordUserRole", b =>
                {
                    b.Property<ulong>("DiscordUserId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("RoleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("DiscordUserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("DiscordUserRoles");
                });

            modelBuilder.Entity("BIC_FHTW.Database.Models.RequestableRole", b =>
                {
                    b.Property<ulong>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("RoleId");

                    b.ToTable("RequestableRoles");
                });

            modelBuilder.Entity("BIC_FHTW.Database.Models.Student", b =>
                {
                    b.Property<string>("EmailString")
                        .HasColumnType("TEXT");

                    b.Property<char>("Association")
                        .HasColumnType("TEXT");

                    b.Property<string>("CourseOfStudy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CourseOfStudyShortname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Group")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Semester")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("EmailString");

                    b.HasIndex("EmailString")
                        .IsUnique();

                    b.ToTable("Students");
                });

            modelBuilder.Entity("BIC_FHTW.Database.Models.DiscordUser", b =>
                {
                    b.HasOne("BIC_FHTW.Database.Models.Student", "Student")
                        .WithOne("DiscordUser")
                        .HasForeignKey("BIC_FHTW.Database.Models.DiscordUser", "StudentMail");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("BIC_FHTW.Database.Models.DiscordUserRole", b =>
                {
                    b.HasOne("BIC_FHTW.Database.Models.DiscordUser", "DiscordUser")
                        .WithMany("DiscordUserRoles")
                        .HasForeignKey("DiscordUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BIC_FHTW.Database.Models.RequestableRole", "RequestableRole")
                        .WithMany("DiscordUserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DiscordUser");

                    b.Navigation("RequestableRole");
                });

            modelBuilder.Entity("BIC_FHTW.Database.Models.DiscordUser", b =>
                {
                    b.Navigation("DiscordUserRoles");
                });

            modelBuilder.Entity("BIC_FHTW.Database.Models.RequestableRole", b =>
                {
                    b.Navigation("DiscordUserRoles");
                });

            modelBuilder.Entity("BIC_FHTW.Database.Models.Student", b =>
                {
                    b.Navigation("DiscordUser");
                });
#pragma warning restore 612, 618
        }
    }
}
