// <auto-generated />

using FHTW.Database.DatabaseContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BIC_FHTW.Database.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.4");

            modelBuilder.Entity("BIC_FHTW.Database.Models.DiscordUser", b =>
                {
                    b.Property<ulong>("DiscordUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActivationMail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActivationToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StudentUid")
                        .HasColumnType("TEXT");

                    b.HasKey("DiscordUserId");

                    b.HasIndex("DiscordUserId")
                        .IsUnique();

                    b.HasIndex("StudentUid")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BIC_FHTW.Database.Models.DiscordUserRole", b =>
                {
                    b.Property<ulong>("DiscordUserId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("RoleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("DiscordUserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("DiscordUserRoles");
                });

            modelBuilder.Entity("BIC_FHTW.Database.Models.RequestableRole", b =>
                {
                    b.Property<ulong>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("RoleId");

                    b.ToTable("RequestableRoles");
                });

            modelBuilder.Entity("BIC_FHTW.Database.Models.Student", b =>
                {
                    b.Property<string>("UID")
                        .HasColumnType("TEXT");

                    b.Property<char>("Association")
                        .HasColumnType("TEXT");

                    b.Property<string>("CourseOfStudy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CourseOfStudyShortname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Group")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Semester")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("UID");

                    b.HasIndex("UID")
                        .IsUnique();

                    b.ToTable("Students");
                });

            modelBuilder.Entity("BIC_FHTW.Database.Models.DiscordUser", b =>
                {
                    b.HasOne("BIC_FHTW.Database.Models.Student", "Student")
                        .WithOne("DiscordUser")
                        .HasForeignKey("BIC_FHTW.Database.Models.DiscordUser", "StudentUid");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("BIC_FHTW.Database.Models.DiscordUserRole", b =>
                {
                    b.HasOne("BIC_FHTW.Database.Models.DiscordUser", "DiscordUser")
                        .WithMany("DiscordUserRoles")
                        .HasForeignKey("DiscordUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BIC_FHTW.Database.Models.RequestableRole", "RequestableRole")
                        .WithMany("DiscordUserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DiscordUser");

                    b.Navigation("RequestableRole");
                });

            modelBuilder.Entity("BIC_FHTW.Database.Models.DiscordUser", b =>
                {
                    b.Navigation("DiscordUserRoles");
                });

            modelBuilder.Entity("BIC_FHTW.Database.Models.RequestableRole", b =>
                {
                    b.Navigation("DiscordUserRoles");
                });

            modelBuilder.Entity("BIC_FHTW.Database.Models.Student", b =>
                {
                    b.Navigation("DiscordUser");
                });
#pragma warning restore 612, 618
        }
    }
}
